version: "3.6"

services:
  postgres-2:
    hostname: postgres-2
    container_name: postgres-2
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    env_file:
      - ./backend/src/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5433:5432"
  api-2:
    hostname: api-2
    container_name: "api-2"
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn backend.src.main:app --host 0.0.0.0  --port 8080"

    depends_on:
      - postgres-2
    ports:
      # - 443:443
      - 8080:8080
    volumes:
      - ./backend:/app
    restart: unless-stopped



volumes:
  postgres_data:
